language: java

git:
  depth: 3

services:
  - docker

jdk:
  - openjdk8

cache:
  directories:
    - '$HOME/.m2/repository'

branches:
  only:
    - feat-zack
    - master

jobs:
  include:
    - stage: build-tutorial-sample
      script:
        - chmod +x $PWD/export.var.sh
        - bash $PWD/export.var.sh
        - source $PWD/export.var.sh
        - echo $commit_id
        - echo $image_tag

        - echo "BUILD JAVA-SE"
        - cd $project_home/java/javase/
        - mvn clean package -DskipTests=true

        - echo "BUILD-SPRING"
        - cd $project_home/java/javaee/spring/spring
        - mvn clean package -DskipTests=true

        - echo "BUILD-SPRING-INTEGRATION"
        - cd $project_home/java/javaee/spring/integration
        - mvn clean package -DskipTests=true

        - echo "BUILD-SPRING-MVC"
        - cd $project_home/java/javaee/spring-mvc
        - mvn clean package -DskipTests=true

        - echo "BUILD-SPRING-BOOT"
        - cd $project_home/java/javaee/spring-boot/integration
        - mvn clean package -DskipTests=true

        - echo "BUILD-SPRING-CLOUD"
        - cd $project_home/java/javaee/spring-cloud/springcloud
        - mvn clean package -DskipTests=true

        - echo "BUILD-SPRING-CLOUD-RELEVANT"
        - cd $project_home/java/javaee/spring-cloud/relevant
        - mvn clean package -DskipTests=true

        - echo "BUILD-JOB"
        - cd $project_home/job/job
        - mvn clean package -DskipTests=true

        - echo "BUILD-MQ"
        - cd $project_home/mq
        - mvn clean package -DskipTests=true

notifications:
  email:
    recipients:
      - zzhang_xz@163.com
    on_success: always # default: change
    on_failure: always # default: always
env:
  project_home: $PWD
  commit_id: 000
  image_tag: 000
  global:
    - GH_REF=git@github.com:Alice52/tutorials-sample.git
