language: java

jdk:
  - openjdk8

cache:
  directories:
  - '$HOME/.m2/repository'

script:
  - echo $HOME
  - echo $PWD
  - echo $GH_REF
  - echo $project_home
  - cd ./java/javaee/spring-boot/integration
  - mvn clean package -DskipTests=true

after_success:
  - echo $pwd
  - echo $project_home
  - cd $project_home
  - echo $pwd
 

branches:
  only:
    - feat-test-travis

notifications:
  email: yes

env:
  project_home: $PWD
  global:
  - GH_REF=git@github.com:Alice52/tutorials-sample.git
