language: java

services:
  - docker

jdk:
  - openjdk8

cache:
  directories:
    - '$HOME/.m2/repository'

branches:
  only:
    - feat-test-travis

jobs:
  include:
    - stage: build-spring-boot
      script:
        - echo `git rev-parse --short HEAD`
        - commit_id=`git rev-parse --short HEAD`
        - echo $commit_id=`git rev-parse --short HEAD`
        - echo $commit_id
        - echo $commit_id2
        - git rev-parse --short HEAD
        - cd $project_home/java/javaee/spring-boot/integration
        - mvn clean package -DskipTests=true

    - stage: build-spring-cloud
      script:
        - cd $project_home/java/javaee/spring-cloud/springcloud
        - mvn clean package -DskipTests=true

notifications:
  email: yes

env:
  project_home: $PWD
  commit_id2: 'git rev-parse --short HEAD'
  global:
    - GH_REF=git@github.com:Alice52/tutorials-sample.git
