language: java

services:
  - docker

jdk:
  - openjdk8

cache:
  directories:
    - '$HOME/.m2/repository'

branches:
  only:
    - feat-test-travis

jobs:
  include:        
    - stage: build-spring-boot
      script:
        - chmod +x $PWD/export.var.sh
        - ./$PWD/export.var.sh
        - echo $commit_id
        - cd $project_home/java/javaee/spring-boot/integration
        - mvn clean package -DskipTests=true

    - stage: build-spring-cloud
      script:
        - cd $project_home/java/javaee/spring-cloud/springcloud
        - mvn clean package -DskipTests=true

notifications:
  email: yes

env:
  project_home: $PWD
  commit_id: 000
  image_tag: 000
  global:
    - GH_REF=git@github.com:Alice52/tutorials-sample.git
