language: java

jdk:
  - openjdk8

cache:
  directories:
  - '$HOME/.m2/repository'

script:
  - echo $HOME
  - echo $PWD
  - echo $GH_REF
  - echo PWD
  - cd ./java/javaee/spring-boot/integration
  - mvn clean package -DskipTests=true

after_success:
  - cd /
  - bash <(curl -s https://codecov.io/bash)  

branches:
  only:
    - feat-test-travis

notifications:
  email: yes

env:
  global:
  - GH_REF=git@github.com:Alice52/tutorials-sample.git
