server:
  port: 80

spring:
  application:
    name: cloud-consumer-order-service
  zipkin:
    base-url: http://101.132.45.28:9411
  sleuth:
    sampler:
      # Probability of requests that should be sampled
      probability: 1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
