#server:
#  port: 9001
#
#spring:
#  application:
#    name: cloud-gateway
#  cloud:
#    gateway:
#      routes:
#        # routing id , should be unique and recommend contact with service name
#        - id: payment-route
#          # matched, then service provider address
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/get/**
#
#        - id: payment-route-lb
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/lb/**
#eureka:
#  instance:
#    hostname: cloud-gateway-service
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#
#logging:
#  level:
#    root: info


# dynamic
server:
  port: 9001

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          # enable register center dynamic create routing according to microsoft service name
          enabled: true
      routes:
        # routing id , should be unique and recommend contact with service name
        - id: payment-route
          # matched, then service provider address
          uri: lb://cloud-provider-payment-service
          filters:
            - AddRequestHeader=X-Request-red, blue
          predicates:
            - After=2020-04-09T21:14:04.596+08:00[Asia/Shanghai]
            - Path=/payment/get/**
            - Cookie=username,zack
            - Header=X-Request-Id,\d+

        - id: payment-route-lb
          uri: lb://cloud-provider-payment-service
          predicates:
            - Path=/payment/lb/**
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

logging:
  level:
    root: info
