server:
  port: 9010

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

logging:
  level:
    ec.*: debug

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    WRITE_DATES_AS_TIMESTAMPS: false
  application:
    name: boot-cache

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"