spring:
  profiles:
    include: common

  redis:
    host: ENC(k6gw0BVkPdxG/JQdsFQHc49HDRDEIGJyth7xEEtmsGUL2TTkl2ciMwBMm5TXGPYV)
    password: ENC(JIczcGuavcI1nX9NbM0YcDyHiQ834QTPhqmczAw+Qr8Nm6wPeq5p5M076HzPSbFF)
    port: ENC(AcXQfYO9iFqD0RYGjek03cmHP3k9y7fl9HEy41cg/mr0xoT4ApjXUbtlpKNK8OCp)