server:
  port: 9010

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

logging:
  level:
    ec.*: debug

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: boot-cache
