server:
  port: 80

spring:
  application:
    name: cloud-seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 101.132.45.28:8848
    alibaba:
      seata:
        # should be match with seata server
        tx-service-group: cloud_seata_tx_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.132.45.28:3306/cloud-seata-order
    username: root
    password: Yu1252068782?

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml