server:
  port: 8006

spring:
  application:
    name: cloud-payment-service
  cloud:
    consul:
      host: 101.132.45.28
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true

