server:
  port: 8080

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    #bean: CustomEncryptorConfigBean

zack: jdbc:mysql://101.132.45.28:3306/project-seckill?useUnicode=true&characterEncoding=utf-8&useSSL=false
