server:
  port: 80

spring:
  application:
    name: cloud-consumer-order-service

eureka:
  client:
    # the feign is just client, so can donot register to eureka
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

ribbon:
  ReadTimeout: 6000
  connectionTimeout: 6000

logging:
  level:
    # feign will log the follow class by specify level
    cn.edu.ntu.springcloud.order.feign.service.FeignService: debug

