server:
  port: 8001

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

spring:
  application:
    name: cloud-provider-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://101.132.45.28:3306/tutorials?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ENC(BwY8lruwIy91OWqgQvsUBeLXjY2TIX7jHcODK0BTCaz9OKaqEi+hxA/NEKu1/W3w)
    password: ENC(c88y1WxnkXsyGM+GTWEovba6qtfUcQ5zv1LV8IOn51Gjf/SCmtCvPAqOlI+i5M7B)
    druid:
      validation-query: SELECT 1
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.ntu.springcloud.payment.entities

logging:
  level:
    root: info
    cn.edu.ntu.springcloud.payment.dao: DEBUG

eureka:
  client:
    # default value
    register-with-eureka: true
    # default value
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    # specify service name
    instance-id: payment8001
    # show IP
    prefer-ip-address: true
    # heartbeat interval time
    lease-renewal-interval-in-seconds: 1
    # eureka will remove this instance after this time if no heartbeat
    lease-expiration-duration-in-seconds: 2
