server:
  undertow:
    io-threads: 2
    worker-threads: 30
    accesslog:
      dir: logs/access/
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b %D "%{i,Referer}" "%{i,User-Agent}"'
      prefix: ${spring.application.name}_access
      suffix: log
      rotate: true

# 加解密根密码
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

# Spring 相关
spring:
  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: "*"

http:
  maxTotal: 2000
  defaultMaxPerRoute: 2000


  datasource:
    username: ENC(3+5Pg+H9L0s1ATmg/xTWLbNt9OeMFguochuRyTl9a4BGbD4lL2SLM8351rdHYhC2)
    password: ENC(MkGdNTchUL+OnF+nvm5YSSjWc7XeHLNab+KV9Wr3fqF1fAbEVLB2urZotLn8nAk1)
    url: ENC(/eIMClN/Pk0zV/9tsO/lVvwakl1gLUvisFxUIqE1nrspX+kVREo86lF3721bhlTYWuq0oRKPQca79vt6kkOiCgLGoMlVDpMj2p4qCdwSydY=)
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    # Configure monitoring statistics interception filters.
    # If removed, the monitoring interface sql cannot collect statistics.
    # Wall is used for the firewall
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

# mybatis-plus
mybatis-plus:
  typeEnumsPackage: boot.mybatis.common.constants.enums
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: 0
      field-strategy: 1
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  root:
    level:
      boot.mybatis: DEBUG
