server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://101.132.45.28:3306/tutorials?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Yu1252068782?
    druid:
      validation-query: SELECT 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.ntu.springcloud.payment.entities
