server:
  port: 8002

spring:
  application:
    name: cloud-provider-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://101.132.45.28:3306/tutorials?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Yu1252068782?
    druid:
      validation-query: SELECT 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.ntu.springcloud.payment.entities

logging:
  level:
    root: info
    cn.edu.ntu.springcloud.payment.dao: DEBUG

eureka:
  client:
    # default value
    register-with-eureka: true
    # default value
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8002
    prefer-ip-address: true



